name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          ls -l /usr/bin/chromedriver
          test -x /usr/bin/chromedriver && echo "Chromedriver funktioniert." || echo "Chromedriver funktioniert nicht."

          # Überprüfe die Versionen von Chrome und Chromedriver
          google-chrome --version
          /usr/bin/chromedriver --version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r selenium-tests/requirements.txt

      - name: Run Tests
        run: |
          pytest selenium-tests/tests/
