name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver
          
          # Überprüfe, ob Google Chrome und Chromedriver korrekt installiert sind
          if [ ! -f /usr/bin/google-chrome ]; then
            echo "Google Chrome wurde nicht korrekt installiert."
            exit 1
          fi
          
          if [ ! -f /usr/bin/chromedriver ]; then
            echo "Chromedriver wurde nicht korrekt installiert."
            exit 1
          fi

          # Setze Chromedriver-Symlink
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          
          # Überprüfe die Versionen
          google-chrome --version
          /usr/bin/chromedriver --version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r selenium-tests/requirements.txt

      - name: Run Tests
        run: |
          pytest selenium-tests/tests/
