name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

          # Install Google Chrome
          sudo apt-get install -y google-chrome-stable

          # Verify installation
          /usr/local/bin/chromedriver --version
          google-chrome --version

          # Setze Chromedriver-Symlink
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          
          # Überprüfe die Versionen
          google-chrome --version
          /usr/bin/chromedriver --version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r selenium-tests/requirements.txt

      - name: Run Tests
        run: |
          pytest selenium-tests/tests/
